os:
  - osx
language: generic
osx_image: xcode10.1
script:
 - swift build -c release -Xswiftc -static-stdlib
 - swift test
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: "./.build/x86_64-apple-macosx10.10/release/iLogYou"
  skip_cleanup: true
  on:
    tags: true
