os:
  - osx
language: generic
osx_image: xcode10.1
script:
  - swift build -c release -Xswiftc -static-stdlib
  - swift test
before_deploy:
  - ./CI/before_deploy.sh
deploy:
  - provider: releases
    api_key: $GH_TOKEN
    file: "ilogyou/.build/x86_64-apple-macosx10.10/release/ilogyou.tar.gz"
    skip_cleanup: true