os:
  - osx
language: generic
osx_image: xcode10.1
script:
  - swift build -c release -Xswiftc -static-stdlib
  - swift test
before_deploy:
  - git config --local user.name $GH_USERNAME
  - git config --local user.email $GH_EMAIL
  - git tag ilogyou
  - tar czvf ilogyou.tar.gz ./.build/x86_64-apple-macosx10.10/release/iLogYou
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: "ilogyou.tar.gz"
  skip_cleanup: true
  overwrite: true