os:
  - osx
language: generic
osx_image: xcode10.1
script:
  - swift build -c release -Xswiftc -static-stdlib
  - swift test
before_deploy:
  - ./CI/before_deploy.sh
deploy:
  - provider: releases
    api_key: $GH_TOKEN
    file: "ilogyou.tar.gz"
    skip_cleanup: true
  - provider: pages
    local-dir: "homebrew-ilogyou"
    repo: "homebrew-ilogyou"
    skip-cleanup: true
    github-token: $GH_TOKEN
    keep-history: true
    on:
      branch: master